<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.l2alLEu' shared service.

return $this->privates['.service_locator.l2alLEu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'viewhandler' => ['privates', '.errored..service_locator.l2alLEu.FOS\\RestBundle\\View\\ViewHandlerInterface', NULL, 'Cannot autowire service ".service_locator.l2alLEu": it references interface "FOS\\RestBundle\\View\\ViewHandlerInterface" but no such service exists. Did you create a class that implements this interface?'],
]);
