<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'eight_points_guzzle.data_collector' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/DataCollector/DataCollectorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/DataCollector/DataCollector.php';
include_once $this->targetDirs[3].'/vendor/eightpoints/guzzle-bundle/src/DataCollector/HttpDataCollector.php';
include_once $this->targetDirs[3].'/vendor/eightpoints/guzzle-bundle/src/Log/LoggerInterface.php';
include_once $this->targetDirs[3].'/vendor/psr/log/Psr/Log/LoggerTrait.php';
include_once $this->targetDirs[3].'/vendor/eightpoints/guzzle-bundle/src/Log/Logger.php';

return $this->privates['eight_points_guzzle.data_collector'] = new \EightPoints\Bundle\GuzzleBundle\DataCollector\HttpDataCollector(($this->services['eight_points_guzzle.logger'] ?? ($this->services['eight_points_guzzle.logger'] = new \EightPoints\Bundle\GuzzleBundle\Log\Logger())), 0.0);
