<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'eight_points_guzzle.client.quote_client' shared service.

include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/Client.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/HandlerStack.php';

$a = \GuzzleHttp\HandlerStack::create();
$a->push(($this->services['eight_points_guzzle.middleware.log.quote_client'] ?? $this->load('getEightPointsGuzzle_Middleware_Log_QuoteClientService.php'))->log(), 'log');
$a->after('log', ($this->services['eight_points_guzzle.middleware.request_time.quote_client'] ?? $this->load('getEightPointsGuzzle_Middleware_RequestTime_QuoteClientService.php')), 'request_time');
$a->push(($this->services['eight_points_guzzle.middleware.symfony_log'] ?? $this->load('getEightPointsGuzzle_Middleware_SymfonyLogService.php')), 'symfony_log');
$a->push(($this->services['eight_points_guzzle.middleware.profile.quote_client'] ?? $this->load('getEightPointsGuzzle_Middleware_Profile_QuoteClientService.php'))->profile(), 'profile');
$a->unshift(($this->services['eight_points_guzzle.middleware.event_dispatch.quote_client'] ?? $this->load('getEightPointsGuzzle_Middleware_EventDispatch_QuoteClientService.php'))->dispatchEvent(), 'events');

return $this->services['eight_points_guzzle.client.quote_client'] = new \GuzzleHttp\Client(['base_uri' => 'https://api-staging.easyterra.com/quotes', 'handler' => $a, 'timeout' => 30.0, 'http_errors' => true, 'headers' => ['User-Agent' => 'EightPointsGuzzleBundle/v7']]);
