<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.l2alLEu.FOS\RestBundle\View\ViewHandlerInterface' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/View/ViewHandlerInterface.php';

return $this->privates['.errored..service_locator.l2alLEu.FOS\RestBundle\View\ViewHandlerInterface'] = new \FOS\RestBundle\View\ViewHandlerInterface();
