<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCIt8Nlz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCIt8Nlz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCIt8Nlz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCIt8Nlz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCIt8Nlz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CIt8Nlz',
    'container.build_id' => '7b6eb970',
    'container.build_time' => 1550841160,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCIt8Nlz');
